# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FGLearnSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FGLearnSwift

  target 'FGLearnSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FGLearnSwiftUITests' do
    # Pods for testing
  end

end
