# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FGLearnSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FGLearnSwift
    pod 'SnapKit'
    pod 'Alamofire'
    pod 'MJRefresh'
    pod 'MBProgressHUD'
    pod 'SwiftyJSON'
end
